# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aabcaaf1fb333960747b35ab936e98ed1d77508433fa822b53d2a9088b2998afbd4e7b2dc5be3467202b9fbb09a215032b67d91ddbfeb7afed40e1e613615d34

test:
  secret_key_base: 3a5e08d0e67ea46052c6d1cc645e8a13046a488d2f807460eaf3afab36c097c4da3d611980610eaf8dc314e4d14847cc2c1e75d4c62eb202f6b46bc0ecbbce2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
